import { createTypes } from 'reduxsauce';

export default createTypes(`
  SET_GAMES_NAVIGATOR
  SET_TEAMS_NAVIGATOR
  SET_SETTINGS_NAVIGATOR
  SET_RULES_NAVIGATOR
  SET_ADMIN_NAVIGATOR
  SET_APP_NAVIGATOR
  SET_MAIN_NAVIGATOR
  
  SET_USER_INFO
  OPEN_DRAWER
  CLOSE_DRAWER
  PUSH_NEW_ROUTE
  REPLACE_ROUTE
  REPLACE_OR_PUSH_ROUTE
  POP_ROUTE
  POP_TO_ROUTE
  LOAD_TASKS_REQUEST
  LOAD_TASKS_ERROR
  LOAD_TASKS_SUCCESS
  SET_HOME_TAB 
  SET_SPINNER_VISIBLE
  SELECT_TOPIC
  SELECT_TOPICS
`);